version: '3.8'

services:
  api:
    build: .
    ports:
      - "8005:8005"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_PATH=/app/models/best_vit_lc25000.pth
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-colon-cancer
    command: http api:8005
    environment:
      - NGROK_AUTHTOKEN=3CXyV6ELbTBjWzk5dkKcHdK6ZGp_ZGjExJkxTYFgfQenxYfp
    ports:
      - "4041:4040"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge